### ISSUE TITLE
Missing tools

### ISSUE THREAD

**Issue by mariana-ochoa** [ElizabethCobian/Quality-Assurance#1]
**SAUCELABS**
_The world's largest continuous testing cloud of web and mobile applications. Access web browsers, mobile emulators, simulators, and real mobile devices._
https://saucelabs.com/

**KOBITON** 
_Mobile testing experience platform that accelerates delivery and testing of mobile apps by offering manual and automated testing on real devices._
https://portal.kobiton.com/login

**Comment by ElizabethCobian** [comment]
@mariana-ochoa adding those tools!
